<?php
/**
 * PositionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * traccar
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PositionTest Class Doc Comment
 *
 * @category    Class
 * @description Position
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PositionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Position"
     */
    public function testPosition()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "device_id"
     */
    public function testPropertyDeviceId()
    {
    }

    /**
     * Test attribute "protocol"
     */
    public function testPropertyProtocol()
    {
    }

    /**
     * Test attribute "device_time"
     */
    public function testPropertyDeviceTime()
    {
    }

    /**
     * Test attribute "fix_time"
     */
    public function testPropertyFixTime()
    {
    }

    /**
     * Test attribute "server_time"
     */
    public function testPropertyServerTime()
    {
    }

    /**
     * Test attribute "outdated"
     */
    public function testPropertyOutdated()
    {
    }

    /**
     * Test attribute "valid"
     */
    public function testPropertyValid()
    {
    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
    }

    /**
     * Test attribute "altitude"
     */
    public function testPropertyAltitude()
    {
    }

    /**
     * Test attribute "speed"
     */
    public function testPropertySpeed()
    {
    }

    /**
     * Test attribute "course"
     */
    public function testPropertyCourse()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "accuracy"
     */
    public function testPropertyAccuracy()
    {
    }

    /**
     * Test attribute "network"
     */
    public function testPropertyNetwork()
    {
    }

    /**
     * Test attribute "additional_properties"
     */
    public function testPropertyAdditionalProperties()
    {
    }

    /**
     * Test attribute "position_type"
     */
    public function testPropertyPositionType()
    {
    }

    /**
     * Test attribute "motion"
     */
    public function testPropertyMotion()
    {
    }

    /**
     * Test attribute "rented"
     */
    public function testPropertyRented()
    {
    }

    /**
     * Test attribute "battery_level"
     */
    public function testPropertyBatteryLevel()
    {
    }

    /**
     * Test attribute "distance"
     */
    public function testPropertyDistance()
    {
    }

    /**
     * Test attribute "total_distance"
     */
    public function testPropertyTotalDistance()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "qr"
     */
    public function testPropertyQr()
    {
    }

    /**
     * Test attribute "battery"
     */
    public function testPropertyBattery()
    {
    }

    /**
     * Test attribute "ride_start"
     */
    public function testPropertyRideStart()
    {
    }

    /**
     * Test attribute "attributes"
     */
    public function testPropertyAttributes()
    {
    }
}
